version: "3"
services:
  springBootApp:
    image: springboot-postgres-ms
    container_name: springboot-dp
    build: ./
    ports:
      - "8080:9090"
    depends_on:
      - postgresqldb
    restart: on-failure
  postgresqldb:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres